### PR TITLE
Fixes #25 and non blocking clEnqueueReadBuffer

### LINKED ISSUE #25: CLKernel::run calls do not wait for completion
In method `CLKernel::run(cl_command_queue *queue, int ND, const size_t *global_ws, const size_t *local_ws)`, the call to `clEnqueueNDRangeKernel` in line 332 does not wait for completion. This can cause wrong result being read into the output buffers.

### PR DESCRIPTION
**Pull request by iame6162013**
This fixes #25 and makes clEnqueueReadBuffer non blocking, the latter should improve performance marginally.

### CODE REVIEW

**Comment by hughperkins** [comment]
sorry, it's been a while, and I'm a bit rusty :P  Do you mind summarizing the changes you're making please?

I know this function is used all over the place, so it's a bit sensitive...

A safe way to modify this without risk by the way would be to give a default parameter, that preserves the existing behavior, but setting it to true gives your new desired behavior.

**Comment by iame6162013** [comment]
I'll list the old and new behavior, because it shows the difference better.

Old: 
1. cl->pushEvent pushes profilingName and kernelFinishedEvent to the back of the vectors if cl->profilingOn == true
2. clEnqueueNDRangeKernel only gets a valid event handle if cl->profilingOn == true
3. Each clEnqueueReadBuffer call does not wait until the kernel has finished executing on the gpu prior to copying memory.
This allows garbage to be written to the buffers.
4. Each clEnqueueReadBuffer call will wait until the memory copy has finished, prior to letting the next copy call start.

New:
1. clEnqueueNDRangeKernel always gets a valid event handle
2. Each copy call may get queued prior to the kernel having finished execution. 
All copy calls wait until the kernel has finished prior to copying data.
3. Each clEnqueueReadBuffer now gets an event handle and the function will return prior to the copy having finished
4. clWaitForEvents waits for all copies to have finished
5. cl->pushEvent pushes profilingName and kernelFinishedEvent to the back of the vectors if cl->profilingOn == true.


You want to maintain old behavior nr. 4 and allow new behavior nr 3 & 4 via an if statement?

**Comment by hughperkins** [comment]
Sounds convincing :) Unit test?  Maybe something like:
- a test that demonstrates the broken behavior, and that the new code fixes it?, and
- tests for some representative use-cases?

> You want to retain old behavior nr. 4 and allow new behavior nr 3 & 4 via an if statement?

Well, I was thinking of having a boolean parameter to the function call. Reading an environment variable on each call sounds ... well I guess not crazy expensive, but... it all adds up.

If the unit tests seem convincing we could simply forego the `if` statement, though maybe we can put something in the `recent news` section, like a one line/sentence description of what's changed.  Maybe something like:

2017 dec 28th:
- @iame6162013 fixed race conditions when reading output buffers

... at the top of 'Recent Changes', https://github.com/hughperkins/EasyCL#recent-changes

Thoughts?

**Comment by hughperkins** [comment]
(just, this code is used all over the place. though now I think about it, all my own projects are bound to a specific commit, so not quite as dangerous as I'm making out, now I think it through a bit. Might be nice to have a couple of unit tests, and the readme update though perhaps?)

**Comment by iame6162013** [comment]
I've just tried adding a unit test for #25 but, the unit test doesn't cause the same bug as the original code, so I won't add it.

I first found bug #25 when programming my coriander plugin. If you're curious my coriander plugin doesn't add anything useful yet.
That brings us to the next topic, if it can show up in coriander(plugins), you should probably select the latest version of EasyCL for your other projects.

I've chosen to leave fast reading behind an if statement until it gets more testing.

If you want to see how much faster fast_reading is, these are the results for my rx 470:

> Non fast_read took:  283us.
Fast_read took:  240us.

with these settings:
> int warmupCycles = 400;
int testCycles = 10000;

I've chosen the setting below as default for the test, because running this is fairly fast, it takes 0.4s on my gpu, and I hope it won't take too long on a cpu :)
>int warmupCycles = 300;
int testCycles = 500;

**Comment by iame6162013** [comment]
Your E5520 does not like fast_read
> Non fast_read took:  210us.
Fast_read took:  281us.

**Comment by hughperkins** [comment]
You can ignore timings on travis. Thats a CPU, not a GPU.

As far as timings, I'm not too worried if timings change slightly, in either direction, on actual GPUs, as long as we don't somehow unintentionally add a new race condition somehow.

**Comment by iame6162013** [comment]
In this code there shouldn't be a new race condition, it is up to you if you want to enable fast read by default or not.

**Comment by hughperkins** [comment]
Awesome, thank you :)

**Pull request merged**
